version: "3.8"
services:
  levantamento:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_URL="mongodb_url"
      - SECREAT=api-levantamento-patrimonial-7200
      - EXPIREIN=7200H